[package]
name = "mlx-serve"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
description = "CLI entrypoint for mlx-serve"

[lints]
workspace = true

[dependencies]
mlx-engine.workspace = true
mlx-server.workspace = true
mlx-models.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
humansize.workspace = true
serde_json.workspace = true
axum.workspace = true
safetensors.workspace = true
num_cpus.workspace = true
